### ISSUE TITLE
REST Interface: Typo in Scheme

### ISSUE THREAD

**Issue by Elscha** [Student-Management-System/StudentMgmt-Backend#8]
The generated REST interface (generated JSON specification) contains a bug at:
```
components.securitySchemas.bearer.scheme: "bearer"
```
Since the REST API accepts the access token only if it is written with a capital letter, it must be:
```
components.securitySchemas.bearer.scheme: "Bearer"
```

**Comment by klingebiel** [comment]
The specification is correct ("bearer"). See https://swagger.io/docs/specification/authentication/bearer-authentication/.
Setting the scheme to "Bearer" will yield an error. Does "Bearer" actually work ? What's the value of the Authorization-Header in both cases ? Is it possible to manually set the header from the application itself ? @Elscha

**Comment by Elscha** [comment]
* If I use the current API spec, I **cannot** connect to the authentication service.
* If I patch it (to "Bearer"), the genarated connectors provide a login functionality.
This is the patched specification that I used: https://raw.githubusercontent.com/Student-Management-System/BE-API-Gen/master/api-json.json

**Comment by Elscha** [comment]
Seems to work now even without a change of the specification
