### ISSUE TITLE
Abfrage (User, Assignment, Kurs) -> Gruppe

### ISSUE THREAD

**Issue by klingebiel** [Student-Management-System/StudentMgmt-Backend#9]
Für einen Benutzer und ein Assignment muss die aktuelle Gruppe ermittelt werden können.
Dieses muss folgende Punkte berücksichtigen:
* Laufende Assignments
* Abgeschlossene/ Bewertete Assignments
* Die jeweils gültige Gruppe, in der sich der User für die jeweilige Abgabe befindet (hat)

Möglich ist auch eine Abfrage, die alle Assignments eines Kurses und Users zurückgibt.

**Comment by klingebiel** [comment]
Als Schnittstelle können die folgenden Endpunkte genutzt werden:

1. http://147.172.178.30:3000/api/#/users/getGroupOfAssignment
Gibt die Gruppe des Nutzers für eine bestimmte Hausaufgabe zurück. Handelt es sich um eine laufende Hausaufgabe, wird momentan die aktuelle Gruppe des Nutzers zurückgegeben. 
2. http://147.172.178.30:3000/api/#/users/getGroupOfAllAssignments
Siehe 1, nur für alle Assignments in einem Kurs. Rückgabetyp ist ein Array aus [Assignment, Group]-Tupeln.

Mir stellt sich bzgl. der internen Implementierung nur noch folgende Frage:
Szenario: 
- 2 laufende Assignments
- Nutzer will nach Abschluss von Assignment 1 seine Gruppe wechseln
- (Automatischer) Gruppenwechsel würde erfolgen, sobald Assignment 1 geschlossen wird

Sollen die obigen Abfragen dann bereits die zukünftige Gruppe für Assignment 2 zurückgeben ?
Aktuell ist dies noch nicht der Fall.
Sind Abgabetermine so dicht, dass die erhöhte Komplexität in Kauf genommen werden sollte ? 🤔 
@Elscha

**Comment by Elscha** [comment]
> Sollen die obigen Abfragen dann bereits die zukünftige Gruppe für Assignment 2 zurückgeben ?
> Aktuell ist dies noch nicht der Fall.
Ich würde sagen, wenn die zweite Abgabe bereits sichtbar ist kann der Teilnehmer kann erst zur dritten Aufgabe wechseln. Andernfalls ist nicht sichergestellt, ob dieser bereits Abgaben zur zweiten Aufgabe getätigt hat.

Mir reicht nur die erste Funktion, jedoch benötigte ich noch eine weitere aus der anderen Perspektive:

Für ein Assingment benötige ich alle Gruppenzusammensetzungen. Ich denke da kommt die folgende Abfrage aktuell am nähesten dran: http://147.172.178.30:3000/api/#/groups/getGroupsFromAssignment Allerdings muss sichergestellt werden, dass diese für alle Assignments gültige Werte zurückliefert.
